name: Repository Status

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  status-check:
    name: Repository Health Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate repository status
      run: |
        echo "# PostgreSQL GDExtension Status Report" > status.md
        echo "Generated on: $(date)" >> status.md
        echo "" >> status.md
        
        # Repository statistics
        echo "## Repository Statistics" >> status.md
        echo "- Total commits: $(git rev-list --all --count)" >> status.md
        echo "- Contributors: $(git log --format='%aN' | sort -u | wc -l)" >> status.md
        echo "- Last commit: $(git log -1 --format='%cd (%h)' --date=short)" >> status.md
        echo "- Repository size: $(du -sh . | cut -f1)" >> status.md
        echo "" >> status.md
        
        # File counts
        echo "## Codebase Overview" >> status.md
        echo "- C++ source files: $(find src/ -name '*.cpp' | wc -l)" >> status.md
        echo "- C++ header files: $(find src/ -name '*.h' | wc -l)" >> status.md
        echo "- Build scripts: $(find build_scripts/ -name '*.sh' -o -name '*.bat' | wc -l)" >> status.md
        echo "- Documentation files: $(find . -name '*.md' | wc -l)" >> status.md
        echo "" >> status.md
        
        # Platform support
        echo "## Platform Support" >> status.md
        echo "- ✅ Linux (x86_64, ARM64)" >> status.md
        echo "- ✅ Windows (x86_64)" >> status.md
        echo "- ✅ macOS (Universal)" >> status.md
        echo "" >> status.md
        
        # Features
        echo "## Features" >> status.md
        echo "- ✅ Connection Pooling" >> status.md
        echo "- ✅ Transaction Management" >> status.md
        echo "- ✅ Async Operations" >> status.md
        echo "- ✅ Parameter Binding" >> status.md
        echo "- ✅ Modern libpqxx API" >> status.md
        echo "" >> status.md
        
        cat status.md

    - name: Check build status
      run: |
        echo "## Recent Workflow Status" >> status.md
        echo "This would show the status of recent workflow runs" >> status.md
        echo "" >> status.md

    - name: Upload status report
      uses: actions/upload-artifact@v4
      with:
        name: repository-status
        path: status.md
        retention-days: 30